# ==========================
# APPLICATION SETTINGS
# ==========================
spring.application.name=gymflow

spring.profiles.active=dev

# ==========================
# SWAGGER
# ==========================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-actuator=true

# ==========================
# JACKSON
# ==========================
spring.jackson.serialization.fail-on-empty-beans=false