# ==========================
# SERVER SETTINGS
# ==========================
server.port=8081
#spring.profiles.active=dev

# ==========================
# DATABASE SETTINGS (MySQL)
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/gym_saas?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# HIKARI CONNECTION POOL
# ==========================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000

# ==========================
# JPA / HIBERNATE SETTINGS
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=true

# ==========================
# SECURITY & JWT SETTINGS
# ==========================
jwt.secret=4f78306e5367526b384a6a4c5a51326d50317134723573367638792f422b452d472b4b425064536756625530
# 10 Hours expiration (in milliseconds)
jwt.expiration=36000000


# ==========================
# LOGGING
# ==========================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG

# ==========================
# N8n Integration
# ==========================
                # test url for n8n
# n8n.webhook-url=http://localhost:5678/webhook-test/gym-notification

    # for production n8n url
# n8n.webhook-url=http://localhost:5678/webhook/gym-notification


# to check post using webhook.site
n8n.webhook-url=https://webhook.site/4cc99121-11d2-473c-8574-97d3f3a1bad0

twilio.whatsapp.api-url=https://api.twilio.com/send-whatsapp

# run every day at 2 AM
scheduler.expiry-reminder.cron=0 0 2 * * ?